### ISSUE TITLE
acquisition.resize() corrupts the data

### ISSUE THREAD

**Issue by mavel101** [ismrmrd/ismrmrd-python#31]
If the acquisition data is resized to a bigger number of samples, the data in the acquisition is corrupted as np.resize() just continuously repeats the data. I would suggest to use np.hstack together with np.zeros to fill the extended data array with zeros instead of the repeated data.

**Comment by hansenms** [comment]
I am not sure that the behavior here is likely to be all that well defined. In general, when you resize an acquisition, I would say you should expect the data to be garbage. One could argue that since the Fourier transform if "circular", you should extend by copying data......but I would not make that argument either. I am labeling this as a wontfix, since it is unclear if the proposed "solution" is actually the right one. If I am missing something here, please re-open with a bit more description and preferably an associated PR.
